version: '3.8'

services:
  # PostgreSQL for analytics data
  postgres-analytics:
    image: postgres:15-alpine
    container_name: sleeper-analytics-db
    environment:
      POSTGRES_DB: sleeper_analytics
      POSTGRES_USER: sleeper
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5432:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data
      - ./src/analytics/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sleeper -d sleeper_analytics"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis (existing cache)
  redis:
    image: redis:7-alpine
    container_name: sleeper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # pgAdmin for database management (optional)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: sleeper-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sleeper.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres-analytics
    restart: unless-stopped

volumes:
  postgres_analytics_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  default:
    name: sleeper-analytics-network